apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration-job
spec:
  template:
    spec:
      containers:
        - name: flyway-migration
          image: eaksprojectweucr.azurecr.io/aks-backend-flyway-migration-service:latest
          command: ["python", "scripts/flyway.py", "migrate"]
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://postgres-master.database.svc.cluster.local:5432/database"
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_WRITE_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_WRITE_PASSWORD
            - name: FLYWAY_SCHEMAS
              value: "public"
      restartPolicy: OnFailure
