apiVersion: v1
kind: Service
metadata:
  name: aks-backend-restapi-service
spec:
  type: LoadBalancer
  selector:
    app: aks-backend-restapi
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
