apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-backend-restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-backend-restapi
  template:
    metadata:
      labels:
        app: aks-backend-restapi
    spec:
      containers:
        - name: restapi
          image: eaksprojectweucr.azurecr.io/aks-backend-restapi-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MODE
              value: "debug"
            - name: DB_TYPE
              value: "POSTGRESQL"
            - name: DB_WRITE_HOST
              value: "postgres-master"
            - name: DB_WRITE_PORT
              value: "5432"
            - name: DB_WRITE_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_WRITE_USER
            - name: DB_WRITE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_WRITE_PASSWORD
            - name: DB_READ_HOST
              value: "postgres-master"
            - name: DB_READ_PORT
              value: "5432"
            - name: DB_READ_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_READ_USER
            - name: DB_READ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_READ_PASSWORD
            - name: DB_NAME
              value: "database"
            - name: CACHE_TYPE
              value: "REDIS_CLUSTER"
            - name: CACHE_HOSTS
              value: "redis-cluster-0.redis-cluster-headless.default.svc.cluster.local:6379,redis-cluster-1.redis-cluster-headless.default.svc.cluster.local:6379,redis-cluster-2.redis-cluster-headless.default.svc.cluster.local:6379"
            - name: CACHE_PORT
              value: "6379"
            - name: CACHE_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CACHE_USER
            - name: CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CACHE_PASSWORD
            - name: CACHE_TTL
              value: "3600"
      restartPolicy: Always
