apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master
spec:
  serviceName: "postgres-master"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: master
  template:
    metadata:
      labels:
        app: postgres
        role: master
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:15
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: "master"
            - name: POSTGRESQL_USERNAME
              value: "postgres"
            - name: POSTGRESQL_PASSWORD
              value: "masterpassword"
            - name: POSTGRESQL_REPLICATION_USER
              value: "repl_user"
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: "repl_password"
            - name: POSTGRESQL_DATABASE
              value: "database"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
spec:
  serviceName: "postgres-replica"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:15
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: "slave"
            - name: POSTGRESQL_USERNAME
              value: "postgres"
            - name: POSTGRESQL_PASSWORD
              value: "masterpassword"
            - name: POSTGRESQL_MASTER_HOST
              value: "postgres-master"
            - name: POSTGRESQL_REPLICATION_USER
              value: "repl_user"
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: "repl_password"
            - name: POSTGRESQL_DATABASE
              value: "database"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
