apiVersion: v1
kind: Service
metadata:
  name: aks-frontend-service
  namespace: application
spec:
  type: LoadBalancer
  selector:
    app: aks-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
